"""Stage 5 - SQLite copy (source tables unchanged + new tables), README and data dictionary."""
from __future__ import annotations

import json
import sqlite3
from pathlib import Path

import pandas as pd

from schema import SCHEMA
from sc_common import SOURCE_NUMERIC, SOURCE_TABLES, Ctx, banner, log, read_typed

SRC_DICT = {  # grain + column meanings of the v1.0.0 tables (from the source DATA_DICTIONARY)
    "suppliers": "One row per supplier.", "products": "One row per product.", "warehouses": "One row per warehouse.",
    "inventory_opening_balances": "One row per product and warehouse.", "purchase_orders": "One row per purchase order.",
    "purchase_order_lines": "One row per purchase-order line.", "inventory_movements": "One row per product, warehouse, and inventory event.",
}


def write_sqlite(ctx: Ctx) -> Path:
    db = ctx.out / ctx.cfg["output"]["sqlite_name"]
    if db.exists():
        db.unlink()
    with sqlite3.connect(db) as con:
        for t in SOURCE_TABLES:  # copy of v1.0.0 exactly as stored (empty strings -> NULL like the source SQLite)
            df = ctx.raw[t].copy()
            for c, k in SOURCE_NUMERIC.get(t, {}).items():
                df[c] = pd.to_numeric(df[c])
            df = df.mask(df.astype(str) == "")
            df.to_sql(t, con, index=False)
        for t in SCHEMA:
            p = ctx.out / "tables" / f"{t}.csv"
            if p.exists():
                pd.read_csv(p, low_memory=False).to_sql(t, con, index=False)
        con.execute("CREATE TABLE dataset_info (key TEXT, value TEXT)")
        con.executemany("INSERT INTO dataset_info VALUES (?, ?)", [("version", ctx.cfg["version"]), ("source_version", ctx.cfg["source_version"]),
                                                                    ("seed", str(ctx.seed)), ("scale", ctx.cfg["scale_name"]), ("license", "CC BY 4.0")])
    log(f"SQLite written: {db.name}")
    return db


def _missing(df: pd.DataFrame, col: str) -> str:
    n = int(df[col].isna().sum()) if col in df else 0
    return "none" if n == 0 else f"{n:,} ({n / len(df):.0%})"


def write_docs(ctx: Ctx):
    rows = {t: len(pd.read_csv(ctx.out / "tables" / f"{t}.csv", usecols=[0])) for t in SCHEMA if (ctx.out / "tables" / f"{t}.csv").exists()}
    dd = ["# Data dictionary - Inventory & Supply Chain Dataset v1.0.0 + extension v1.1.0-ext", "",
          f"Coverage: {ctx.calib['window_start']} through {ctx.calib['window_end']} (RM ledger starts earlier to feed early production runs).", "",
          "Original v1.0.0 tables are unchanged; see the source DATA_DICTIONARY.md for them. New tables follow.", ""]
    for t, spec in SCHEMA.items():
        if t not in rows:
            continue
        df = read_typed(ctx, t)
        dd += [f"## `{t}`", "", f"Grain: {spec['grain']}  ", f"Rows: {rows[t]:,}", "", "| Column | What it means | Data type | Missing values | Key |", "|---|---|---|---|---|"]
        for col, typ, desc, nullable, key in spec["columns"]:
            dd.append(f"| `{col}` | {desc} | {typ} | {_missing(df, col)} | {key} |")
        dd.append("")
    dd += ["## Relationships", ""]
    for t, spec in SCHEMA.items():
        for col, rt, rc in spec["fks"]:
            dd.append(f"- `{t}.{col}` -> `{rt}.{rc}` (many-to-one)")
    dd += ["- `decisions.footprint_ids`, `disruption_events.anchor_ids`, `commitments.evidence_ids` -> JSON arrays of ids from any table "
           "(snapshot rows are referenced as `rm_id|plant_id|snapshot_date`).",
           "- `memory_corpus.jsonl.source_record_ids` / `entity_ids` -> ids in any table; `eval_questions.jsonl.gold_doc_ids` -> `memory_corpus.doc_id`.", ""]
    (ctx.out / "DATA_DICTIONARY.md").write_text("\n".join(dd))

    pats = json.loads((ctx.out / "planted_patterns.json").read_text())["patterns"] if (ctx.out / "planted_patterns.json").exists() else []
    n_docs = sum(1 for _ in open(ctx.out / "memory_corpus.jsonl")) if (ctx.out / "memory_corpus.jsonl").exists() else 0
    n_q = sum(1 for _ in open(ctx.out / "eval_questions.jsonl")) if (ctx.out / "eval_questions.jsonl").exists() else 0
    rd = f"""# Inventory & Supply Chain Dataset - Memory & Decision Agent extension (v1.1.0-ext)

Synthetic, fictional extension of **Analytics Engineering, "Inventory & Supply Chain Dataset v1.0.0"**
(https://www.analyticsengineering.com/datasets/inventory-supply-chain), licensed **CC BY 4.0**
(https://creativecommons.org/licenses/by/4.0/). The original seven tables are included **unchanged**; everything
else was generated by the code in this folder (seed {ctx.seed}, scale `{ctx.cfg['scale_name']}`).
All suppliers, plants, brands, materials, people and events are fictional. No PII. This extension is also released under CC BY 4.0.

## What is added

| Part | Tables / files |
|---|---|
| Structure & BOM | plants, products_ext, raw_materials, bill_of_materials, rm_supplier_catalog, contracts |
| RM operations | rm_inventory_opening_balances, rm_purchase_orders, rm_purchase_order_lines, rm_po_revisions, rm_inventory_movements, rm_inventory_snapshots_weekly, production_runs |
| Demand | product_demand_weekly |
| Institutional memory | disruption_events, event_impacts, event_links, negotiations, decisions, commitments, supplier_scorecard_monthly |
| Memory corpus | memory_corpus.jsonl ({n_docs:,} docs; one line = one Hindsight retain item) |
| Evaluation | eval_questions.jsonl ({n_q} questions), holdout_scenarios.json, planted_patterns.json |

Row counts: {", ".join(f"{t} {n:,}" for t, n in rows.items())}.

Files: `tables/*.csv` (+ `tables/parquet/*.parquet` when pyarrow is installed), `{ctx.cfg['output']['sqlite_name']}`
(the v1.0.0 tables plus all new tables), `calibration.json` (Stage 0 profile), `DATA_DICTIONARY.md`.

## How it was built (and the rules it keeps)

1. **Profile first** (`profile.py`) - every scale / rate / category parameter comes from the source (see `calibration.json`).
2. **Additive only** - source rows are never modified; `validate.py` checks row counts + content hashes of the inputs and of the SQLite copy.
3. **Causality** - RM deliveries follow supplier reliability, quoted lead time, country / season shocks and planted patterns;
   RM stock is simulated by a time-phased MRP. Existing FG lateness is uniform in v1.0.0 (not related to reliability), so FG-side
   events are *mined* clusters (binomial tests) and the RM side is built to explain existing late / short FG receipts.
4. **Cascade back-fill** - for ~12% of eligible late/short make-product FG lines: RM PO slip (rm_po_revisions) -> RM stock below safety ->
   run blocked at its planned start (`production_runs.delay_reason_code = rm_shortage`) -> the existing FG receipt is late. Every chain is
   re-checked against the full stock trajectory (strict date order, run could not have started earlier, no negative stock).
5. **Outcomes are computed, not sampled** - decision costs / stockout days, commitment statuses and scorecards come from the trajectories
   (`consequences.py` holds the deterministic cost model shared with the holdout simulator).
6. **Identities** - RM: opening + cumulative movements = weekly on-hand; consumption = produced_qty x qty_per_unit x (1 + scrap_pct/100);
   demand: fulfilled_units = -SUM(existing sale quantity_change) per product / warehouse / week.

## Key modelling notes

- Make products (`products_ext.sourcing_mode = make`) are produced at `plant_id`; their existing FG PO is read as the replenishment order from
  the plant, and the PO's supplier as the tolling partner operating the line.
- `product_demand_weekly` is sparse (weeks with demand or a non-zero forecast) because source sales are intermittent
  ({ctx.calib['sales']['pair_week_nonzero_share']:.2%} of product-warehouse-weeks have sales).
- `unfulfilled_units > 0` only where existing stock hit <= 0 or a logged event explains it (customer allocation during a supply cascade,
  DC disruption, demand spike).
- `decisions.outcome_attribution` (extension column): as_expected | context_shift (worked before, failed under different conditions) |
  bad_luck (best ex-ante, failed through an outside event) | decision_quality.
- Extra key columns not in the brief: `rm_supplier_catalog.catalog_id`, `rm_po_revisions.revision_id`, `rm_purchase_orders.order_type`,
  `commitments.evidence_ids`, corpus field `supersedes`.

## Memory corpus (`memory_corpus.jsonl`)

Fields: doc_id, timestamp (ISO-8601, business hours), context, content, doc_type, entity_ids, source_record_ids, split (memory | holdout),
is_noise, supersedes. Docs are rendered from structured facts by a seeded template grammar (>=15 variants per doc type) and form stories of
3+ docs written days/weeks apart by different roles. ~27% are low-signal noise; >=10% update or supersede an earlier doc. Docs dated from
{ctx.calib['holdout_start']} are `split=holdout` and must not be ingested. Optional `--llm-narratives` rewrites docs through a cached,
resumable, provider-agnostic LLM interface with a fact-lock check (`llm_narratives.py`).

## Planted patterns

""" + "\n".join(f"- **{p['pattern_id']}** {p['name']} - {p['description']} Effect: `{json.dumps(p['effect'])}`, p={p['p_value']}." for p in pats) + f"""

## Reproduce

```
pip install pandas numpy scipy pyyaml pyarrow
python run_all.py --input <folder|zip|sqlite of v1.0.0> --output out --seed {ctx.seed} --scale default   # ~5-10 min
python run_all.py --input ... --output out_small --scale small                                          # dev corpus (~300 docs)
python validate.py --input ... --output out                                                              # fail-loud checks
python hindsight_loader.py --corpus out/memory_corpus.jsonl --bank supply-chain-memory --dry-run
```

## Attribution

Source data: Analytics Engineering, "Inventory & Supply Chain Dataset v1.0.0",
https://www.analyticsengineering.com/datasets/inventory-supply-chain - CC BY 4.0. Changes: new tables, corpus and evaluation files added;
original tables unchanged. Synthetic educational data; not a real company; no industry benchmarks implied.
"""
    (ctx.out / "README.md").write_text(rd)
    log("README.md + DATA_DICTIONARY.md written")


def run(ctx: Ctx):
    banner("STAGE 5 - SQLite copy, README, data dictionary")
    write_sqlite(ctx)
    write_docs(ctx)
